import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { createPageMetadata } from "@/lib/seo/metadata";
import { SITE_NAME } from "@/lib/seo/site";

export const metadata: Metadata = createPageMetadata({
  title: "How to Record Sales for a Small Business",
  description: "Learn what to record for each business sale, how to handle cash and credit sales, and how to review your sales without double-counting payments.",
  path: "/guides/how-to-record-sales-for-small-business",
});

export default function Page() {
  return <main className="min-h-screen bg-[#F8F8F6] text-plum"><header className="border-b border-plum/10 bg-plum text-white"><div className="mx-auto flex max-w-[900px] items-center justify-between px-5 py-5 lg:px-8"><Link href="/" className="font-heading text-xl font-bold text-white">{SITE_NAME}</Link><Link href="/guides" className="text-sm font-semibold text-white/70 hover:text-white">All guides</Link></div></header><article className="mx-auto max-w-[900px] px-5 pb-20 pt-14 lg:px-8 lg:pb-28 lg:pt-20"><p className="openbooks-eyebrow text-terracotta">Sales</p><h1 className="mt-4 font-heading text-[clamp(2.7rem,6vw,5.3rem)] font-extrabold leading-[0.95] tracking-[-0.05em]">How to record sales for a small business.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-plum/65">A useful sales record makes each transaction easy to find, total and reconcile. The goal is to capture enough information to understand what was sold and what was actually paid.</p><div className="mt-12 space-y-10 text-base leading-8 text-plum/70"><section><h2 className="font-heading text-2xl font-extrabold sm:text-3xl">Record these basics</h2><p className="mt-4">For each sale, record the date, customer if known, description of the item or service, quantity, amount, payment status and payment method. Use a unique reference or invoice number when the transaction is formal.</p></section><section><h2 className="font-heading text-2xl font-extrabold sm:text-3xl">Treat credit sales differently</h2><p className="mt-4">A customer can receive the goods today and pay later. Keep the sale as the original transaction, then record later payments separately. This prevents a payment from being counted as another sale.</p></section><section><h2 className="font-heading text-2xl font-extrabold sm:text-3xl">Review daily and weekly totals</h2><p className="mt-4">At the end of a period, compare total sales with money collected and outstanding balances. When the numbers do not agree, inspect the underlying transactions rather than guessing from the bank balance alone.</p></section></div><div className="mt-14 rounded-3xl bg-plum p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-pale-sage">Free tool</p><h2 className="mt-2 font-heading text-2xl font-extrabold">Start with OpenBooks or calculate your profit.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Record sales in OpenBooks or use the free calculator to understand what those sales mean for profit.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-terracotta px-5 py-3 text-sm font-bold text-white">Start for free <ArrowRight size={16} /></Link><Link href="/tools/profit-calculator" className="inline-flex items-center gap-2 rounded-xl border border-white/20 px-5 py-3 text-sm font-bold text-white">Profit calculator <ArrowRight size={16} /></Link></div></div></article></main>;
}
