import Link from "next/link";
import { ArrowRight, Check, ReceiptText } from "lucide-react";
import { OpenBooksBrandMark } from "@/components/openbooks-brand-mark";

const benefits = ["Professional invoices without design work", "Clear due dates and outstanding balances", "Simple records for every client", "Payment options that fit your workflow", "Receipts ready when a client pays"];

export default function ForFreelancersPage() {
  return <main className="min-h-screen bg-[#F8F8F6] text-[#503047]"><header className="bg-[#503047] text-white"><div className="mx-auto flex max-w-[1100px] items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-2.5 font-heading text-xl font-bold"><OpenBooksBrandMark size={32} /><span>Open<span className="text-[#C05746]">Books</span></span></Link><Link href="/" className="text-sm font-semibold text-white/75 hover:text-white">Back home</Link></div></header><section className="mx-auto max-w-[1100px] px-5 py-24 lg:py-32"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#C05746]">For freelancers</p><h1 className="mt-5 max-w-4xl font-heading text-[clamp(3rem,6vw,5.8rem)] font-extrabold leading-[0.94] tracking-[-0.05em]">Spend less time formatting invoices. More time doing the work.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#6F6670]">From a ₦20,000 design job to a ₦500,000 website project, OpenBooks keeps the client, invoice, payment and receipt connected.</p><div className="mt-14 grid gap-4 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[32px] bg-[#C05746] p-7 text-white sm:p-9"><ReceiptText size={30}/><p className="mt-8 text-xs font-semibold uppercase tracking-[0.18em] text-[#D0E3C4]">Client invoice</p><p className="mt-3 font-heading text-4xl font-bold">₦150,000</p><p className="mt-2 text-sm text-white/70">Website design · Due 05 Sept</p><div className="mt-8 rounded-2xl bg-white p-4 text-[#503047]"><div className="flex justify-between text-sm"><span>Amount due</span><span className="font-bold">₦150,000</span></div><div className="mt-3 h-px bg-[#E5E3DF]"/><div className="mt-3 text-xs text-[#918A91]">Bank transfer · Paystack</div></div></div><div className="grid gap-4 sm:grid-cols-2">{benefits.map((item) => <div key={item} className="rounded-3xl border border-[#E5E3DF] bg-white p-6"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#D0E3C4]"><Check size={16}/></div><p className="mt-5 text-sm font-semibold leading-6">{item}</p></div>)}</div></div><div className="mt-12 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#503047] px-6 py-3.5 text-sm font-semibold text-white">Start for free <ArrowRight size={16}/></Link><Link href="/guide" className="inline-flex items-center justify-center rounded-2xl border border-[#503047]/15 px-6 py-3.5 text-sm font-semibold">See how it works</Link></div></section></main>;
}
