import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { OpenBooksBrandMark } from "@/components/openbooks-brand-mark";

const points = ["No OpenBooks account required", "See the invoice clearly", "Use only the payment methods the business enabled", "Pay online when Paystack is available", "Keep a clear receipt after payment"];

export default function ForCustomersPage() {
  return <main className="min-h-screen bg-[#F8F8F6] text-[#503047]"><header className="bg-[#503047] text-white"><div className="mx-auto flex max-w-[1100px] items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-2.5 font-heading text-xl font-bold"><OpenBooksBrandMark size={32} /><span>Open<span className="text-[#C05746]">Books</span></span></Link><Link href="/" className="text-sm font-semibold text-white/75 hover:text-white">Back home</Link></div></header><section className="mx-auto max-w-[1100px] px-5 py-24 lg:py-32"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#C05746]">For customers</p><h1 className="mt-5 max-w-4xl font-heading text-[clamp(3rem,6vw,5.8rem)] font-extrabold leading-[0.94] tracking-[-0.05em]">Open the invoice. Pay. Done.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#6F6670]">You should not need another account just to pay a small business. OpenBooks keeps the customer side of the experience simple.</p><div className="mt-12 rounded-[32px] bg-[#503047] p-6 text-white sm:p-8"><div className="grid gap-8 md:grid-cols-[1fr_0.8fr]"><div><p className="text-xs uppercase tracking-[0.18em] text-[#D0E3C4]">Example invoice</p><p className="mt-4 font-heading text-4xl font-bold">₦85,000</p><p className="mt-2 text-sm text-white/60">Ade Phone Repairs · iPhone screen replacement</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button className="rounded-2xl bg-[#C05746] px-5 py-3 text-sm font-semibold text-white">Pay online</button><button className="rounded-2xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-white">View bank details</button></div></div><div className="rounded-3xl bg-white/5 p-5"><p className="text-sm font-semibold">What you get</p><div className="mt-4 space-y-3">{points.map((p) => <div key={p} className="flex gap-3 text-sm leading-6 text-white/75"><Check className="mt-0.5 shrink-0 text-[#ADC698]" size={16}/>{p}</div>)}</div></div></div></div><div className="mt-10"><Link href="/" className="inline-flex items-center gap-2 rounded-2xl border border-[#503047]/15 bg-white px-6 py-3.5 text-sm font-semibold">Back to OpenBooks <ArrowRight size={16}/></Link></div></section></main>;
}
